# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Manish <xtermous@gmail.com>
  description: A comprehensive Ansible role for deploying and configuring Nginx web server on Red Hat family systems with SSL/TLS support, security headers, and firewall integration.
  company: Manish PSYS

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: https://github.com/padminisys/nginx/issues

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: GPL-2.0-or-later

  min_ansible_version: 2.9

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: CentOS
      versions:
        - 7
        - 8
        - 9
    - name: Fedora
      versions:
        - 34
        - 35
        - 36
        - 37
        - 38
        - 39
        - 40

  galaxy_tags:
    - nginx
    - web
    - http
    - https
    - ssl
    - tls
    - security
    - firewall
    - redhat
    - centos
    - fedora
    - webserver
    - reverse-proxy
    - load-balancer

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
