---
driver:
  name: podman
platforms:
  - name: centos10-http
    image: quay.io/centos/centos:stream10
    pre_build_image: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    environment:
      container: podman
    systemd: true
    capabilities:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    stop_signal: SIGRTMIN+3

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: root
        ansible_become: false
        ansible_connection: podman
        nginx_ssl_enabled: false
        nginx_http_port: 80

verifier:
  name: ansible 