---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - python3-pip
          - python3-cryptography
          - openssl
          - firewalld
          - which
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_os_family == "RedHat" 